namespace APIService.DTOs
{
    public class DrinkCreateDTO
    {
        // create a single drink item 
        // ID will be generated by MongoDB 
        public string? DrinkName { get; set; }
        public string? DrinkType { get; set; }
        public double Price { get; set; }
        public string? Extras { get; set; }
        public string? SupplierId { get; set; }
    }
}
